### ISSUE TITLE
Rearrange files according to programming language

### ISSUE THREAD

**Issue by rahulatrkm** [rahulatrkm/ds_and_algo#52]
Since there are many new PRs coming and I see there isn't any proper structure in the repository is being maintained. 

Can someone pick this issue of reaaranging the files? 

Please comment here that you are picking this task.

**Comment by Abhinav092003** [comment]
yess i can do please assign me

**Comment by rahulatrkm** [comment]
Sure @Abhinav092003 Please work on it and mention in contributing.md, how others should follow the str.

**Comment by rahulatrkm** [comment]
@Abhinav092003 Can you share ETA for the restructuring?

**Comment by Abhinav092003** [comment]
Okkk
